version: '3.8'

# Use root/example as user/password credentials

services:

  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MARIADB_ROOT_PASSWORD: example
  #   ports:
  #     - 3306:3306

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 9000:9000
      - 5173:5173 # vue port
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
